/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./components/base/PageStatus/404.vue')['default']
    500: typeof import('./components/base/PageStatus/500.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    Popup: typeof import('./components/base/Popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectLanguage: typeof import('./components/base/SelectLanguage.vue')['default']
    Skeleton: typeof import('./components/base/Skeleton.vue')['default']
  }
}
